name: Auto EUserv

on:
  schedule:
    - cron: '0 14 * * SUN'  # 每周日 UTC 时间 14:00 运行
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Check required secrets
      run: |
        REQUIRED_SECRETS=(
          EUSERV_USERNAME
          EUSERV_PASSWORD
          TRUECAPTCHA_USERID
          TRUECAPTCHA_APIKEY
          TG_BOT_TOKEN
          TG_USER_ID
          MAILPARSER_DOWNLOAD_URL_ID
        )
        MISSING_SECRETS=()
        for SECRET in "${REQUIRED_SECRETS[@]}"; do
          VALUE="${{ secrets[SECRET] }}"
          if [ -z "$VALUE" ]; then
            MISSING_SECRETS+=($SECRET)
          fi
        done

        if [ ${#MISSING_SECRETS[@]} -ne 0 ]; then
          echo "❌ Missing required secrets: ${MISSING_SECRETS[*]}"
          exit 1
        else
          echo "✅ All required secrets are set."
        fi

    - name: Run script
      env:
        EUSERV_USERNAME: ${{ secrets.EUSERV_USERNAME }}
        EUSERV_PASSWORD: ${{ secrets.EUSERV_PASSWORD }}
        TRUECAPTCHA_USERID: ${{ secrets.TRUECAPTCHA_USERID }}
        TRUECAPTCHA_APIKEY: ${{ secrets.TRUECAPTCHA_APIKEY }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}
        MAILPARSER_DOWNLOAD_URL_ID: ${{ secrets.MAILPARSER_DOWNLOAD_URL_ID }}
      run: python Github_Action.py
